FROM eclipse-temurin:17-jre

WORKDIR /app

# Copy dependencies
COPY dailyfeed-content/build/libs/*.jar app.jar

# Environment variables
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

# Expose ports
EXPOSE 8080 5005

# Set user
USER 1000:1000

# Run the application
ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:+UseG1GC", "-Dfile.encoding=UTF-8", "-jar", "app.jar"]